### ISSUE TITLE
1.8.1/2 broke this card

### ISSUE THREAD

**Issue by broyuken** [thomasloven/lovelace-auto-entities#175]
HA OS 2021.3.3
auto entities 1.8.1 or 1.8.2

```
type: 'custom:auto-entities'
card:
  type: entities
entities:
  - switch.guest_mode
filter:
  include:
    - entity_id: person.*
      state: home
  exclude:
    - entity_id: person.me
    - entity_id: person.wife
sort:
  method: domain
  reverse: true
```

I have the card above set up to display the guests in my house (people connected to my wifi). It also displays the guest mode switch at the top before any guests are listed. This was all working perfectly until I upgraded to 1.8.1 and .2. 

On 1.8.1 the card won't display and neither will anything else that would display under it. It seems to break the view at that point down. 
It spits out the following in my logs when I try to display the page.
```
2021-03-09 20:19:30 ERROR (MainThread) [homeassistant.helpers.event] Error while processing state change for person.brian
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 280, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 435, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/zone/trigger.py", line 60, in zone_automation_listener
    from_match = condition.zone(hass, zone_state, from_s) if from_s else False
  File "/usr/src/homeassistant/homeassistant/helpers/condition.py", line 668, in zone
    raise ConditionErrorMessage("zone", "no zone specified")
homeassistant.exceptions.ConditionErrorMessage: In 'zone' condition: no zone specified
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 280, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 435, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/zone/trigger.py", line 60, in zone_automation_listener
    from_match = condition.zone(hass, zone_state, from_s) if from_s else False
  File "/usr/src/homeassistant/homeassistant/helpers/condition.py", line 668, in zone
    raise ConditionErrorMessage("zone", "no zone specified")
homeassistant.exceptions.ConditionErrorMessage: In 'zone' condition: no zone specified
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 280, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 435, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/zone/trigger.py", line 60, in zone_automation_listener
    from_match = condition.zone(hass, zone_state, from_s) if from_s else False
  File "/usr/src/homeassistant/homeassistant/helpers/condition.py", line 668, in zone
    raise ConditionErrorMessage("zone", "no zone specified")
homeassistant.exceptions.ConditionErrorMessage: In 'zone' condition: no zone specified
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 280, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 435, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/zone/trigger.py", line 60, in zone_automation_listener
    from_match = condition.zone(hass, zone_state, from_s) if from_s else False
  File "/usr/src/homeassistant/homeassistant/helpers/condition.py", line 668, in zone
    raise ConditionErrorMessage("zone", "no zone specified")
homeassistant.exceptions.ConditionErrorMessage: In 'zone' condition: no zone specified
```

On 1.8.1 the card itself doesn't display anything but the rest of my lovelace loads in fine. I get the following in my logs.
```
2021-03-09 20:21:18 ERROR (MainThread) [homeassistant] Error doing job: protocol.resume_writing() failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/transports.py", line 294, in _maybe_resume_protocol
    self._protocol.resume_writing()
  File "/usr/local/lib/python3.8/asyncio/sslproto.py", line 517, in resume_writing
    self._app_protocol.resume_writing()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/base_protocol.py", line 31, in resume_writing
    assert self._paused
AssertionError
```

This all works perfectly fine in 1.8.0 with no errors.

**Comment by masonevans** [comment]
I'm seeing something similar.  When I remove the `sort` everything works.  Any configuration of `sort` seems to break it and everything below it.

**Comment by thomasloven** [comment]
Should be fixed in 1.8.3

**Comment by broyuken** [comment]
Just installed 1.8.3 and it's still broken. There's no errors in the logs but the switch isn't showing up.

**Comment by thomasloven** [comment]
What about the browser consle?

**Comment by broyuken** [comment]
Nothing that I can see. 1.8.4 didn’t fix it either.

**Comment by broyuken** [comment]
This seems to be fixed when I remove the 

sort:
  method: domain 

out of the card. Soon as I put it back in my switch disappears.

**Comment by thomasloven** [comment]
And it's still breaking everything after this card as well?
Please tell me what version number your browser log says you have installed.

**Comment by broyuken** [comment]
No, everything else loads fine on 1.8.4. Just the card doesn’t display. And I primarily use the iOS app.

**Comment by thomasloven** [comment]
Would you mind giving me a new error description then, just to make sure I understand everything correctly?
Including Home Assistant and auto-entities version, fault description, MWE and any output from the browser console.

**Comment by broyuken** [comment]
Updated Issue Description:

auto entities version 1.8.4

card code:
```
type: 'custom:auto-entities'
card:
  type: entities
entities:
  - switch.guest_mode
filter:
  include:
    - entity_id: person.*
      state: home
  exclude:
    - entity_id: person.me
    - entity_id: person.wifey
sort:
  method: domain
  reverse: true
show_empty: true
```
Preview of card shows this:
![image](https://user-images.githubusercontent.com/1593391/111791036-3544b080-8899-11eb-83d2-ed2761441054.png)

Same exact card in lovelace shows this:
![image](https://user-images.githubusercontent.com/1593391/111791150-54434280-8899-11eb-8850-738c15a9eebe.png)

If I change the code to not exclude my person entity so the filter is not empty:
```
type: 'custom:auto-entities'
card:
  type: entities
entities:
  - switch.guest_mode
filter:
  include:
    - entity_id: person.*
      state: home
  exclude:
    - entity_id: person.wifey
sort:
  method: domain
  reverse: true
show_empty: true
```
Then the card shows up as expected:
![image](https://user-images.githubusercontent.com/1593391/111791481-9f5d5580-8899-11eb-9214-90e1f80c02d9.png)

My theory is that if the filter does not return anything the card does not display anything, even if the 
entities:
  - switch.guest_mode
portion exists which should show the entity even if the filter filters it out.

**Comment by thomasloven** [comment]
I can't shake the feeling that this is an incredibly persistent cache problem.
Would you mind testing in incognito mode or a different browser?

Because you DID clear the cache after upgrading? With the button in the bottom of the app settings?

**Comment by broyuken** [comment]
Yes I cleared that, and the issue persists across multiple browsers and the ios app.

**Comment by thomasloven** [comment]
The fact that this is inside a stack card turned out to be the key. Please try release 1.8.5.

**Comment by broyuken** [comment]
Still need to test a few more browsers but I think this is fixed. My other issue with the history graph is in a grid and has not been fixed yet.
