### ISSUE TITLE
history-graph doesn't work with 1.8.2

### ISSUE THREAD

**Issue by andreypolyak** [thomasloven/lovelace-auto-entities#178]
Hi, thanks for this great card!

So, for a long time I had this code in my lovelace:
```YAML
  - type: custom:auto-entities
    show_empty: false
    card:
      type: history-graph
    filter:
      include:
        - entity_id: person.andrey
        - entity_id: device_tracker.wifi_andrey*
        - entity_id: device_tracker.ble_andrey*
        - entity_id: device_tracker.ble_*_andrey*
        - entity_id: device_tracker.icloud_andrey*
        - entity_id: device_tracker.ha_andrey*
        - entity_id: input_select.andrey_location
    sort:
      method: entity_id
```

Screenshot (version 1.7.0):
![2021-03-11 21_36_32-Window](https://user-images.githubusercontent.com/7446762/110837369-2fa40500-82b2-11eb-8791-cf6b314afa12.png)

But when I updated to 1.8.2 it stopped working, I only get red rectangle:
![2021-03-11 21_32_24-Window](https://user-images.githubusercontent.com/7446762/110837654-8f9aab80-82b2-11eb-9349-7e03fc63a519.png)

I also got this error in the console:
```
card history-graph Error: You must include at least one entity
    value chunk.c00343a31472caee9fe1.js:2621
    s chunk.bf78bb32ee89f3425ccf.js:3096
    d chunk.bf78bb32ee89f3425ccf.js:3096
    c chunk.bf78bb32ee89f3425ccf.js:3096
    a chunk.bf78bb32ee89f3425ccf.js:3096
    update_card auto-entities.js:194
chunk.bf78bb32ee89f3425ccf.js:3096
```

Downgrading to 1.7.0 helped, card is once again working.

**Comment by hmmbob** [comment]
Inspired by https://github.com/thomasloven/lovelace-auto-entities/issues/175#issuecomment-797151667 , can you try removing the `sort:` key and the line below it?

**Comment by thomasloven** [comment]
Should be fixed in 1.8.3

**Comment by broyuken** [comment]
It was not. Also not fixed in 1.8.4

**Comment by andreypolyak** [comment]
@thomasloven, unfortunately I still have the same issue even on 1.8.4

```
card history-graph Error: You must include at least one entity
    value chunk.c00343a31472caee9fe1.js:2621
    s chunk.bf78bb32ee89f3425ccf.js:3096
    d chunk.bf78bb32ee89f3425ccf.js:3096
    c chunk.bf78bb32ee89f3425ccf.js:3096
    a chunk.bf78bb32ee89f3425ccf.js:3096
    update_card auto-entities.js:194
    update_all auto-entities.js:194
    setConfig auto-entities.js:194
    setConfig auto-entities.js:194
    s chunk.bf78bb32ee89f3425ccf.js:3096
    d chunk.bf78bb32ee89f3425ccf.js:3096
    d chunk.bf78bb32ee89f3425ccf.js:3096
    c chunk.bf78bb32ee89f3425ccf.js:3096
    a chunk.bf78bb32ee89f3425ccf.js:3096
    value chunk.c00343a31472caee9fe1.js:3706
    _cards chunk.c00343a31472caee9fe1.js:3404
    value chunk.c00343a31472caee9fe1.js:3404
    s chunk.bf78bb32ee89f3425ccf.js:3096
    d chunk.bf78bb32ee89f3425ccf.js:3096
    c chunk.bf78bb32ee89f3425ccf.js:3096
    a chunk.bf78bb32ee89f3425ccf.js:3096
    value chunk.bcc24dc7f2504ad36740.js:2974
    _cards chunk.bcc24dc7f2504ad36740.js:2974
    value chunk.bcc24dc7f2504ad36740.js:2974
    value chunk.bcc24dc7f2504ad36740.js:2974
    performUpdate app.ce7ee54a.js:12773
    _enqueueUpdate app.ce7ee54a.js:12773
    requestUpdateInternal app.ce7ee54a.js:12773
    initialize app.ce7ee54a.js:12773
    C app.ce7ee54a.js:12773
    i chunk.bcc24dc7f2504ad36740.js:2974
    value chunk.bcc24dc7f2504ad36740.js:3796
    _debouncedConfigChanged chunk.bcc24dc7f2504ad36740.js:2974
    i app.ce7ee54a.js:12773
    setTimeout handler*i/< app.ce7ee54a.js:12773
    handleEvent app.ce7ee54a.js:12773
    __boundHandleEvent app.ce7ee54a.js:12773
    t card-mod.js:1
    <anonymous> card-mod.js:5
chunk.bf78bb32ee89f3425ccf.js:3096
    c chunk.bf78bb32ee89f3425ccf.js:3096
    a chunk.bf78bb32ee89f3425ccf.js:3096
    update_card auto-entities.js:194
    update_all auto-entities.js:194
    setConfig auto-entities.js:194
    (Async: VoidFunction)
    setConfig auto-entities.js:194
    s chunk.bf78bb32ee89f3425ccf.js:3096
    d chunk.bf78bb32ee89f3425ccf.js:3096
    d chunk.bf78bb32ee89f3425ccf.js:3096
    c chunk.bf78bb32ee89f3425ccf.js:3096
    a chunk.bf78bb32ee89f3425ccf.js:3096
    value chunk.c00343a31472caee9fe1.js:3706
    _cards chunk.c00343a31472caee9fe1.js:3404
    value chunk.c00343a31472caee9fe1.js:3404
    s chunk.bf78bb32ee89f3425ccf.js:3096
    d chunk.bf78bb32ee89f3425ccf.js:3096
    c chunk.bf78bb32ee89f3425ccf.js:3096
    a chunk.bf78bb32ee89f3425ccf.js:3096
    value chunk.bcc24dc7f2504ad36740.js:2974
    _cards chunk.bcc24dc7f2504ad36740.js:2974
    value chunk.bcc24dc7f2504ad36740.js:2974
    value chunk.bcc24dc7f2504ad36740.js:2974
    performUpdate app.ce7ee54a.js:12773
    _enqueueUpdate app.ce7ee54a.js:12773
    requestUpdateInternal app.ce7ee54a.js:12773
    initialize app.ce7ee54a.js:12773
    C app.ce7ee54a.js:12773
    i chunk.bcc24dc7f2504ad36740.js:2974
    value chunk.bcc24dc7f2504ad36740.js:3796
    _debouncedConfigChanged chunk.bcc24dc7f2504ad36740.js:2974
    i app.ce7ee54a.js:12773
    (Async: setTimeout handler)
    i app.ce7ee54a.js:12773
    handleEvent app.ce7ee54a.js:12773
    __boundHandleEvent app.ce7ee54a.js:12773
    t card-mod.js:1
    <anonymous> card-mod.js:5
```

**Comment by thomasloven** [comment]
Do you get anything with a different card type, like `entities`?

**Comment by broyuken** [comment]
I have the same issue with history graphs, works fine with entities. Would it make sense to roll back all your recent changes and try coding them again? It seems like there were a lot of breaking changes brought in with these newer versions.

**Comment by thomasloven** [comment]
Is this in a vertical stack?

**Comment by thomasloven** [comment]
If so, please try release 1.8.5.

**Comment by broyuken** [comment]
I think that may have fixed my guest mode one, but my history graphs are in a grid card and that didn’t get fixed.

**Comment by Kirmas** [comment]
Same problem. 1.8.5 didn`t fix it. 
For me: this is in a vertical stack. 
Problem only with history-graph, entities card work perfect.

**Comment by broyuken** [comment]
Any thoughts on how to resolve this for history graphs?

**Comment by Masterz69** [comment]
Confirm: auto-entities 1.8.5 fails to work with history-graph card.
See below very simple setup - fine with entities card, but NOT with history-graph.
Result: ```card history-graph Error: You must include at least one entity```

```
    cards:
      - type: vertical-stack
        cards:
          - type: custom:auto-entities
            card:
              type: entities
#              type: history-graph
#              title: Link Quality
#              hours_to_show: 72
#              refresh_interval: 180
            filter:
              include:
                - entity_id: "sensor.*_linkquality"
            sort:
              method: name
```

**Comment by thomasloven** [comment]
Try release 1.9.0

**Comment by broyuken** [comment]
nope, still just showing a red bar

**Comment by thomasloven** [comment]
Ok.
I'm quite certain I finally got it with 1.9.1

**Comment by broyuken** [comment]
I think that did it, great work, thank you!

**Comment by Kirmas** [comment]
fixed for me too
