### ISSUE TITLE
Card layout/sizing

### ISSUE THREAD

**Issue by mynameisdaniel32** [thomasloven/lovelace-auto-entities#37]
Had a go at moving to auto-entities (from monster card) a few weeks ago and had this same issue, just gave it another go and I'm having the same problem.

The Lovelace card layout when using auto-entities doesn't seem to shuffle things correctly, it seems to treat all cards as having a height of something small, regardless of if they have lots of entities.

As an example:
Using Monster Card:
![image](https://user-images.githubusercontent.com/24840952/68821980-9c6bb700-06df-11ea-9f21-a3b0114e3b6e.png)

Using Auto-Entities:
![image](https://user-images.githubusercontent.com/24840952/68821998-a8f00f80-06df-11ea-90d4-c0ab5b80dfa0.png)

This example doesn't seem too bad/unusable, however, it's doing the same behaviour with an auto-entities card with twice the entities (which makes the page long unnecessarily long and require scrolling).

Tried the usual clearing cache, etc.

**Comment by thomasloven** [comment]
The layouting of custom cards is pretty much random and depends strongly on which order things are loaded in by your browser.

You may have better results if you use my [layout-card](https://github.com/thomasloven/lovelace-layout-card) in just the default configuration, but there's still no guarantee.

**Comment by quthla** [comment]
Tried auto-entities few months ago and this issue is the reason I switched back to monster.

First is monster, second auto-entities with messed up layout. Blue area caused by screenshot so don't mind it.

Scripts, Geräte and Automationen are all monster / auto-entities cards.

![monstercard](https://user-images.githubusercontent.com/30180109/68890847-0906a600-0720-11ea-8279-8500bf95e77d.png)
![autoent](https://user-images.githubusercontent.com/30180109/68890846-0906a600-0720-11ea-857e-38f670aef34e.png)

**Comment by thomasloven** [comment]
I think I fixed it

**Comment by mynameisdaniel32** [comment]
Thanks - updated to 1.4 but still an issue for me here (and a little worse), seems anything with 2 or 3 cards puts them all into a single column regardless of how long they are (previously it was only doing it to the pages with 2 cards). I can see the cards reload once populated, but that reload action actually makes it worse haha.

The gif below might give you some idea, when the page loads, it automatically goes to 2 columns wide, now it does the auto reload thing and all ends up in 1 column.

![2019-11-15_9-35-30](https://user-images.githubusercontent.com/24840952/68903527-65eb7600-078b-11ea-8399-bfdc5354f769.gif)

**Comment by quthla** [comment]
Yes, not fixed for me too. When I change the window size or open the inspector, the layout will align correctlly.

**Comment by thomasloven** [comment]
Ok. How about now (release 1.5)?

**Comment by quthla** [comment]
Looks good

**Comment by mynameisdaniel32** [comment]
Beautiful! Thanks Thomas!
