### ISSUE TITLE
Show if empty in Sections view

### ISSUE THREAD

**Issue by woniol** [thomasloven/lovelace-auto-entities#433]
If _Show if empty_ is set to false, card is shown in the Sections view, taking additional space.
Not sure if this is for auto-entities card or the new Sections view case?

**Comment by luisleonardo** [comment]
I can confirm and provide a screenshot.

The space in the middle is created by 6 card with "show_empty: false".

![image](https://github.com/thomasloven/lovelace-auto-entities/assets/4042791/246d32b9-2cbe-4ace-89e7-cea51c4c1952)

**Comment by Drun555** [comment]
These gaps driving me crazy

🙏
![IMG_6983](https://github.com/thomasloven/lovelace-auto-entities/assets/44411820/b479dc46-47e6-429a-a182-2965d78e9d99)

**Comment by luisleonardo** [comment]
Any news? I still can't use the sections due to this bug and I don't even know if the problem is from auto-entities or Lovelace :(

**Comment by spartan117aut** [comment]
I have the same problem. The problem with conditional cards has been fixed [here](https://github.com/home-assistant/frontend/issues/19925), but empty auto-entities cards still occupy space. See attached screenshots.

Edit mode:
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/67920531/209a452c-0569-45d7-a9b4-a69e91fea81d)

Actual display:
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/67920531/9cb52d18-65e2-4237-8190-1ce99b965a57)

**Comment by igorsantos07** [comment]
I was going to open a bug on HA, as a follow-up to https://github.com/home-assistant/frontend/issues/20352 (where they state the solution for the problem is using the new Visibility option, but that effectively causes us to recreate and duplicate the filters from auto-entities; **not** a solution). My thesis was that they should reduce `--row-height` and/or make it themeable, so we can fix it for our specific scenarios...

However, while writing it, I realize the default `entities-filter` does not show this behavior. Thus, I guess this is a bug with this custom card, which should not generate an empty card component on the UI (instead of generating an empty one).
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/532299/dfaf6988-296c-424b-b701-333d1470ab9b)

**Comment by skynet01** [comment]
Any updates or solutions to fix this even if manually?

**Comment by christian1986** [comment]
Any news on this? Highly limit the usage of the card😕

**Comment by MrAdam** [comment]
I've made a PR that fixes this issue - I hope @thomasloven has time to look at it 😄

**Comment by pmharris77** [comment]
@MrAdam It seems the latest version of HA has fixed this for me

**Comment by MrAdam** [comment]
> @MrAdam It seems the latest version of HA has fixed this for me

Same here! Well, that's great, since it looks like @thomasloven is not active at the moment 👍 
I'll leave my PR though, as it makes the code mimmic how other components does it.

One thing I did notice, is that if it's empty, I can't see it in edit mode, which makes it hard to edit using the GUI.
I might look into that if this repo ever becomes active again 😄

**Comment by jackwilsdon** [comment]
It looks like this is still an issue if an `auto-entities` card is the only thing in a section:

![image](https://github.com/user-attachments/assets/262c625c-98a0-472b-888c-5f1672c04c81)

The large gap in the top left is where the `auto-entities` card is.

**Comment by MrAdam** [comment]
> It looks like this is still an issue if a hidden `auto-entities` card is the only thing in a section:
> 
> ![image](https://private-user-images.githubusercontent.com/1843197/382937858-262c625c-98a0-472b-888c-5f1672c04c81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3OTEzMTUsIm5iZiI6MTczMDc5MTAxNSwicGF0aCI6Ii8xODQzMTk3LzM4MjkzNzg1OC0yNjJjNjI1Yy05OGEwLTQ3MmItODg4Yy01ZjE2NzJjMDRjODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMDcxNjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDU2MjlkNTM4MjFiYTM0ZGFlNWQzMzg0MTVlNzlmN2I0ZmJkMDJmNWQxMjM3MTE3OTAxNzNhNTFhOGFiZjM0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-olBTpicDNiFTzZuh3nwHjcSyKKKENTBeHwR7bDcznU)
> 
> The large gap in the top left is where the `auto-entities` card is.

Can you try the fix from my branch and see if it works? If yes, then maybe we should get it merged.

**Comment by sambarre** [comment]
I saw a mentioned in the thread that this was fixed by an update to HA itself, but I still seem to be having the issue 
![image](https://github.com/user-attachments/assets/015bb413-1890-4b45-8093-1f5c15384564)
This gap in my vertical stack card is a few auto entities cards that are hidden most of the time 

How would I go about testing this branch if I wanted to?

**Comment by jackwilsdon** [comment]
@MrAdam sadly it doesn't fix it.

![image](https://github.com/user-attachments/assets/4c0075e7-b984-4fb3-8186-09537a25cbab)

![image](https://github.com/user-attachments/assets/a264a474-87a0-419f-b7f2-5f0d83d8dbff)

Tried with the card both inside and outside a section.
